# This override file should be used when running this service in isolation
# to provide dependencies and expose ports for local testing

services:
  ${{ values.project_name }}:
    build:
      target: development
    image: ${{ values.project_name }}-development
    container_name: ${{ values.project_name }}-development
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - ./app:/home/node/app
      - ./package.json:/home/node/package.json
      