# For documentation on how to use, please go here: https://github.com/DEFRA/adp-aso-helm-library?tab=readme-ov-file#adp-platform-azure-service-operator-helm-library-chart.
# You may create Queues, Topics, Subscriptions, Storage Accounts, Databases and Role Assignments on these here.
{# Conditional rendering the resources based on the selections in backstage portal #}
{%- if values.app_infra_service_bus_check == 'queue' %}
namespaceQueues:
  - name: ${{ values.app_infra_service_bus_resource_name }}
    {%- if values.app_infra_service_bus_resource_type == 'subscriber' %}
    owner: 'no'
    {%- endif %}
    roleAssignments:
      {%- if values.app_infra_service_bus_resource_type == 'publisher' %}
      - roleName: 'QueueSender'
      {%- endif %}
      {%- if values.app_infra_service_bus_resource_type == 'subscriber' %}
      - roleName: 'QueueReceiver'
      {%- endif %}
{%- endif %}

{%- if values.app_infra_service_bus_check == 'topic' %}
namespaceTopics:
  - name: ${{ values.app_infra_service_bus_resource_name }}
    {%- if values.app_infra_service_bus_resource_type == 'subscriber' %}
    owner: 'no'
    {%- endif %}
    roleAssignments:
      {%- if values.app_infra_service_bus_resource_type == 'publisher' %}
      - roleName: 'TopicSender'
      {%- endif %}
      {%- if values.app_infra_service_bus_resource_type == 'subscriber' %}
      - roleName: 'TopicReceiver'
      {%- endif %}
{%- endif %}

{%- if values.app_infra_postgres_db_check == 'yes' %}
postgres:
  db:
    name: ${{ values.app_infra_postgres_db_resource_name }}
    charset: UTF8
    collation: en_US.utf8
{%- endif %}
