apiVersion: v2
name: ${{ (values.service_name + "-infra") | yaml }}
description: ${{ ("A ASO Helm chart to deploy the " +  values.service_name + " Infrastructure") | yaml }}
version: 0.0.1
dependencies:
  - name: adp-aso-helm-library
    version: ^2.0.0
    repository: https://raw.githubusercontent.com/defra/adp-helm-repository/main/adp-aso-helm-library
